### ISSUE TITLE
what is the methodology to rudn this project on my computer?

### ISSUE THREAD

**Issue by guaillazaca** [ImagingYeditepe/Segmentation-of-Teeth-in-Panoramic-X-ray-Image#1]
Hello, first of all I want to congratulate you on the project, it is very good, what is the methodology to run this project on my computer? Cheers

**Comment by SerdarHelli** [comment]
Hello Guaillazaca, 
I will make the necessary adjustments and additions when this study is published. Unfortunately, I shared in a very confusing way. :(

**Comment by SerdarHelli** [comment]
Now , You can easily run with one click .  Cheers  :rocket: :rocket:   :rocket:
